# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KA4K98JI8821IaSdn-BZhWpKT1U7PXGM
"""

from __future__ import print_function
from torch import nn, optim, cuda
from torch.utils import data
from torchvision import datasets, transforms
import torch.nn.functional as F
import time
import tensorflow as tf


'''
from tensorflow.keras.datasets import cifar10
(train_X, train_y), (test_X, test_y) = cifar10.load_data()
train_dataset = train_X.astype("float") / 255.0
test_dataset = test_X.astype("float") / 255.0 

print(f"train_X: {train_X.shape}, test_X = {test_X.shape}") 
'''



train_dataset = datasets.CIFAR10(root='./data',train=True,transform=transforms.ToTensor(),download=True) 

test_dataset = datasets.CIFAR10(root='./data',train=False,transform=transforms.ToTensor())



batch_size = 64
device = 'cuda' if cuda.is_available() else 'cpu'
print(f'Training MNIST Model on {device}\n{"=" * 44}')



# Data Loader (Input Pipeline)
train_loader = data.DataLoader(dataset=train_dataset,
                                           batch_size=batch_size,
                                           shuffle=True)

test_loader = data.DataLoader(dataset=test_dataset,
                                          batch_size=batch_size,
                                          shuffle=False)
print(train_dataset)

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.l1 = nn.Linear(32*32*3, 2024)  #
        self.l2 = nn.Linear(2024, 1312)
        self.l3 = nn.Linear(1312, 800)
        self.l4 = nn.Linear(800, 400)
        self.l5 = nn.Linear(400, 150)
        self.l6 = nn.Linear(150, 10)

    def forward(self, x):
        x = x.view(-1, 32*32*3)  # Flatten the data (n, 1, 28, 28)-> (n, 32*32*3)
        x = F.relu(self.l1(x))
        x = F.relu(self.l2(x))
        x = F.relu(self.l3(x))
        x = F.relu(self.l4(x))
        x = F.relu(self.l5(x))
        return self.l6(x)


model = Net()
model.to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.045, momentum=0.5)
#m 0.01/0.5 40%   0.01/0.7 48%    0.05/07 44  0.05/0.5 48

def train(epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % 10 == 0:
            print('Train Epoch: {} | Batch Status: {}/{} ({:.0f}%) | Loss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))


def test():
    model.eval()
    test_loss = 0
    correct = 0
    for data, target in test_loader:
        data, target = data.to(device), target.to(device)
        output = model(data)
        # sum up batch loss
        test_loss += criterion(output, target).item()
        # get the index of the max
        pred = output.data.max(1, keepdim=True)[1]
        correct += pred.eq(target.data.view_as(pred)).cpu().sum()

    test_loss /= len(test_loader.dataset)
    print(f'===========================\nTest set: Average loss: {test_loss:.4f}, Accuracy: {correct}/{len(test_loader.dataset)} '
          f'({100. * correct / len(test_loader.dataset):.0f}%)')


if __name__ == '__main__':
    since = time.time()
    for epoch in range(1, 10):
        epoch_start = time.time()
        train(epoch)
        m, s = divmod(time.time() - epoch_start, 60)
        print(f'Training time: {m:.0f}m {s:.0f}s')
        test()
        m, s = divmod(time.time() - epoch_start, 60)
        print(f'Testing time: {m:.0f}m {s:.0f}s')

    m, s = divmod(time.time() - since, 60)
    print(f'Total Time: {m:.0f}m {s:.0f}s\nModel was trained on {device}!')

'''Files already downloaded and verified
Training MNIST Model on cpu
============================================
Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: ToTensor()
Train Epoch: 1 | Batch Status: 0/50000 (0%) | Loss: 2.306153
Train Epoch: 1 | Batch Status: 640/50000 (1%) | Loss: 2.306131
Train Epoch: 1 | Batch Status: 1280/50000 (3%) | Loss: 2.300875
Train Epoch: 1 | Batch Status: 1920/50000 (4%) | Loss: 2.299556
Train Epoch: 1 | Batch Status: 2560/50000 (5%) | Loss: 2.303054
Train Epoch: 1 | Batch Status: 3200/50000 (6%) | Loss: 2.303152
Train Epoch: 1 | Batch Status: 3840/50000 (8%) | Loss: 2.301803
Train Epoch: 1 | Batch Status: 4480/50000 (9%) | Loss: 2.306228
Train Epoch: 1 | Batch Status: 5120/50000 (10%) | Loss: 2.295115
Train Epoch: 1 | Batch Status: 5760/50000 (12%) | Loss: 2.296277
Train Epoch: 1 | Batch Status: 6400/50000 (13%) | Loss: 2.296151
Train Epoch: 1 | Batch Status: 7040/50000 (14%) | Loss: 2.296850
Train Epoch: 1 | Batch Status: 7680/50000 (15%) | Loss: 2.304078
Train Epoch: 1 | Batch Status: 8320/50000 (17%) | Loss: 2.285164
Train Epoch: 1 | Batch Status: 8960/50000 (18%) | Loss: 2.289802
Train Epoch: 1 | Batch Status: 9600/50000 (19%) | Loss: 2.290433
Train Epoch: 1 | Batch Status: 10240/50000 (20%) | Loss: 2.280169
Train Epoch: 1 | Batch Status: 10880/50000 (22%) | Loss: 2.292318
Train Epoch: 1 | Batch Status: 11520/50000 (23%) | Loss: 2.261072
Train Epoch: 1 | Batch Status: 12160/50000 (24%) | Loss: 2.256906
Train Epoch: 1 | Batch Status: 12800/50000 (26%) | Loss: 2.255170
Train Epoch: 1 | Batch Status: 13440/50000 (27%) | Loss: 2.192804
Train Epoch: 1 | Batch Status: 14080/50000 (28%) | Loss: 2.131927
Train Epoch: 1 | Batch Status: 14720/50000 (29%) | Loss: 2.182942
Train Epoch: 1 | Batch Status: 15360/50000 (31%) | Loss: 2.188468
Train Epoch: 1 | Batch Status: 16000/50000 (32%) | Loss: 2.184472
Train Epoch: 1 | Batch Status: 16640/50000 (33%) | Loss: 2.130717
Train Epoch: 1 | Batch Status: 17280/50000 (35%) | Loss: 2.175938
Train Epoch: 1 | Batch Status: 17920/50000 (36%) | Loss: 2.080250
Train Epoch: 1 | Batch Status: 18560/50000 (37%) | Loss: 2.170667
Train Epoch: 1 | Batch Status: 19200/50000 (38%) | Loss: 2.241639
Train Epoch: 1 | Batch Status: 19840/50000 (40%) | Loss: 2.020830
Train Epoch: 1 | Batch Status: 20480/50000 (41%) | Loss: 2.061183
Train Epoch: 1 | Batch Status: 21120/50000 (42%) | Loss: 1.967847
Train Epoch: 1 | Batch Status: 21760/50000 (43%) | Loss: 2.011175
Train Epoch: 1 | Batch Status: 22400/50000 (45%) | Loss: 2.015491
Train Epoch: 1 | Batch Status: 23040/50000 (46%) | Loss: 2.078171
Train Epoch: 1 | Batch Status: 23680/50000 (47%) | Loss: 2.092454
Train Epoch: 1 | Batch Status: 24320/50000 (49%) | Loss: 2.304393
Train Epoch: 1 | Batch Status: 24960/50000 (50%) | Loss: 2.034552
Train Epoch: 1 | Batch Status: 25600/50000 (51%) | Loss: 2.097335
Train Epoch: 1 | Batch Status: 26240/50000 (52%) | Loss: 1.998855
Train Epoch: 1 | Batch Status: 26880/50000 (54%) | Loss: 1.958589
Train Epoch: 1 | Batch Status: 27520/50000 (55%) | Loss: 2.064810
Train Epoch: 1 | Batch Status: 28160/50000 (56%) | Loss: 2.091589
Train Epoch: 1 | Batch Status: 28800/50000 (58%) | Loss: 2.034364
Train Epoch: 1 | Batch Status: 29440/50000 (59%) | Loss: 2.013856
Train Epoch: 1 | Batch Status: 30080/50000 (60%) | Loss: 1.964983
Train Epoch: 1 | Batch Status: 30720/50000 (61%) | Loss: 2.140694
Train Epoch: 1 | Batch Status: 31360/50000 (63%) | Loss: 2.023019
Train Epoch: 1 | Batch Status: 32000/50000 (64%) | Loss: 2.198919
Train Epoch: 1 | Batch Status: 32640/50000 (65%) | Loss: 1.810305
Train Epoch: 1 | Batch Status: 33280/50000 (66%) | Loss: 2.033788
Train Epoch: 1 | Batch Status: 33920/50000 (68%) | Loss: 1.945171
Train Epoch: 1 | Batch Status: 34560/50000 (69%) | Loss: 1.940205
Train Epoch: 1 | Batch Status: 35200/50000 (70%) | Loss: 1.909015
Train Epoch: 1 | Batch Status: 35840/50000 (72%) | Loss: 1.909760
Train Epoch: 1 | Batch Status: 36480/50000 (73%) | Loss: 1.929321
Train Epoch: 1 | Batch Status: 37120/50000 (74%) | Loss: 1.966430
Train Epoch: 1 | Batch Status: 37760/50000 (75%) | Loss: 1.870810
Train Epoch: 1 | Batch Status: 38400/50000 (77%) | Loss: 1.779283
Train Epoch: 1 | Batch Status: 39040/50000 (78%) | Loss: 1.927665
Train Epoch: 1 | Batch Status: 39680/50000 (79%) | Loss: 1.846740
Train Epoch: 1 | Batch Status: 40320/50000 (81%) | Loss: 1.913306
Train Epoch: 1 | Batch Status: 40960/50000 (82%) | Loss: 1.990379
Train Epoch: 1 | Batch Status: 41600/50000 (83%) | Loss: 1.905341
Train Epoch: 1 | Batch Status: 42240/50000 (84%) | Loss: 1.894126
Train Epoch: 1 | Batch Status: 42880/50000 (86%) | Loss: 2.020723
Train Epoch: 1 | Batch Status: 43520/50000 (87%) | Loss: 1.847782
Train Epoch: 1 | Batch Status: 44160/50000 (88%) | Loss: 1.975054
Train Epoch: 1 | Batch Status: 44800/50000 (90%) | Loss: 2.069345
Train Epoch: 1 | Batch Status: 45440/50000 (91%) | Loss: 1.856714
Train Epoch: 1 | Batch Status: 46080/50000 (92%) | Loss: 2.031122
Train Epoch: 1 | Batch Status: 46720/50000 (93%) | Loss: 1.932410
Train Epoch: 1 | Batch Status: 47360/50000 (95%) | Loss: 2.091168
Train Epoch: 1 | Batch Status: 48000/50000 (96%) | Loss: 2.002367
Train Epoch: 1 | Batch Status: 48640/50000 (97%) | Loss: 1.958046
Train Epoch: 1 | Batch Status: 49280/50000 (98%) | Loss: 1.930105
Train Epoch: 1 | Batch Status: 49920/50000 (100%) | Loss: 1.858311
Training time: 1m 29s
===========================
Test set: Average loss: 0.0326, Accuracy: 2276/10000 (23%)
Testing time: 1m 34s
Train Epoch: 2 | Batch Status: 0/50000 (0%) | Loss: 2.221920
Train Epoch: 2 | Batch Status: 640/50000 (1%) | Loss: 1.919929
Train Epoch: 2 | Batch Status: 1280/50000 (3%) | Loss: 1.682004
Train Epoch: 2 | Batch Status: 1920/50000 (4%) | Loss: 1.926175
Train Epoch: 2 | Batch Status: 2560/50000 (5%) | Loss: 1.870236
Train Epoch: 2 | Batch Status: 3200/50000 (6%) | Loss: 1.882472
Train Epoch: 2 | Batch Status: 3840/50000 (8%) | Loss: 2.074003
Train Epoch: 2 | Batch Status: 4480/50000 (9%) | Loss: 1.870834
Train Epoch: 2 | Batch Status: 5120/50000 (10%) | Loss: 2.015087
Train Epoch: 2 | Batch Status: 5760/50000 (12%) | Loss: 1.888077
Train Epoch: 2 | Batch Status: 6400/50000 (13%) | Loss: 1.863465
Train Epoch: 2 | Batch Status: 7040/50000 (14%) | Loss: 2.019964
Train Epoch: 2 | Batch Status: 7680/50000 (15%) | Loss: 1.879016
Train Epoch: 2 | Batch Status: 8320/50000 (17%) | Loss: 1.761460
Train Epoch: 2 | Batch Status: 8960/50000 (18%) | Loss: 1.920237
Train Epoch: 2 | Batch Status: 9600/50000 (19%) | Loss: 1.681372
Train Epoch: 2 | Batch Status: 10240/50000 (20%) | Loss: 1.853310
Train Epoch: 2 | Batch Status: 10880/50000 (22%) | Loss: 1.764989
Train Epoch: 2 | Batch Status: 11520/50000 (23%) | Loss: 1.797562
Train Epoch: 2 | Batch Status: 12160/50000 (24%) | Loss: 1.740119
Train Epoch: 2 | Batch Status: 12800/50000 (26%) | Loss: 1.787502
Train Epoch: 2 | Batch Status: 13440/50000 (27%) | Loss: 1.870576
Train Epoch: 2 | Batch Status: 14080/50000 (28%) | Loss: 1.881830
Train Epoch: 2 | Batch Status: 14720/50000 (29%) | Loss: 1.811189
Train Epoch: 2 | Batch Status: 15360/50000 (31%) | Loss: 1.685686
Train Epoch: 2 | Batch Status: 16000/50000 (32%) | Loss: 1.807089
Train Epoch: 2 | Batch Status: 16640/50000 (33%) | Loss: 1.844835
Train Epoch: 2 | Batch Status: 17280/50000 (35%) | Loss: 1.889539
Train Epoch: 2 | Batch Status: 17920/50000 (36%) | Loss: 1.901481
Train Epoch: 2 | Batch Status: 18560/50000 (37%) | Loss: 1.769582
Train Epoch: 2 | Batch Status: 19200/50000 (38%) | Loss: 1.861594
Train Epoch: 2 | Batch Status: 19840/50000 (40%) | Loss: 1.572778
Train Epoch: 2 | Batch Status: 20480/50000 (41%) | Loss: 1.675964
Train Epoch: 2 | Batch Status: 21120/50000 (42%) | Loss: 1.883794
Train Epoch: 2 | Batch Status: 21760/50000 (43%) | Loss: 1.729749
Train Epoch: 2 | Batch Status: 22400/50000 (45%) | Loss: 1.783467
Train Epoch: 2 | Batch Status: 23040/50000 (46%) | Loss: 1.836939
Train Epoch: 2 | Batch Status: 23680/50000 (47%) | Loss: 1.752602
Train Epoch: 2 | Batch Status: 24320/50000 (49%) | Loss: 1.642545
Train Epoch: 2 | Batch Status: 24960/50000 (50%) | Loss: 1.550314
Train Epoch: 2 | Batch Status: 25600/50000 (51%) | Loss: 1.838575
Train Epoch: 2 | Batch Status: 26240/50000 (52%) | Loss: 1.719203
Train Epoch: 2 | Batch Status: 26880/50000 (54%) | Loss: 1.951567
Train Epoch: 2 | Batch Status: 27520/50000 (55%) | Loss: 1.907409
Train Epoch: 2 | Batch Status: 28160/50000 (56%) | Loss: 1.710292
Train Epoch: 2 | Batch Status: 28800/50000 (58%) | Loss: 1.778100
Train Epoch: 2 | Batch Status: 29440/50000 (59%) | Loss: 1.838728
Train Epoch: 2 | Batch Status: 30080/50000 (60%) | Loss: 1.847814
Train Epoch: 2 | Batch Status: 30720/50000 (61%) | Loss: 1.866889
Train Epoch: 2 | Batch Status: 31360/50000 (63%) | Loss: 1.824541
Train Epoch: 2 | Batch Status: 32000/50000 (64%) | Loss: 1.818016
Train Epoch: 2 | Batch Status: 32640/50000 (65%) | Loss: 1.665988
Train Epoch: 2 | Batch Status: 33280/50000 (66%) | Loss: 1.718526
Train Epoch: 2 | Batch Status: 33920/50000 (68%) | Loss: 1.742360
Train Epoch: 2 | Batch Status: 34560/50000 (69%) | Loss: 1.914935
Train Epoch: 2 | Batch Status: 35200/50000 (70%) | Loss: 1.603509
Train Epoch: 2 | Batch Status: 35840/50000 (72%) | Loss: 1.699105
Train Epoch: 2 | Batch Status: 36480/50000 (73%) | Loss: 1.669325
Train Epoch: 2 | Batch Status: 37120/50000 (74%) | Loss: 1.561075
Train Epoch: 2 | Batch Status: 37760/50000 (75%) | Loss: 1.735070
Train Epoch: 2 | Batch Status: 38400/50000 (77%) | Loss: 1.762113
Train Epoch: 2 | Batch Status: 39040/50000 (78%) | Loss: 1.766976
Train Epoch: 2 | Batch Status: 39680/50000 (79%) | Loss: 1.667369
Train Epoch: 2 | Batch Status: 40320/50000 (81%) | Loss: 1.836044
Train Epoch: 2 | Batch Status: 40960/50000 (82%) | Loss: 1.786728
Train Epoch: 2 | Batch Status: 41600/50000 (83%) | Loss: 1.769909
Train Epoch: 2 | Batch Status: 42240/50000 (84%) | Loss: 1.628734
Train Epoch: 2 | Batch Status: 42880/50000 (86%) | Loss: 1.541151
Train Epoch: 2 | Batch Status: 43520/50000 (87%) | Loss: 1.804887
Train Epoch: 2 | Batch Status: 44160/50000 (88%) | Loss: 1.825693
Train Epoch: 2 | Batch Status: 44800/50000 (90%) | Loss: 1.615141
Train Epoch: 2 | Batch Status: 45440/50000 (91%) | Loss: 1.675038
Train Epoch: 2 | Batch Status: 46080/50000 (92%) | Loss: 1.760851
Train Epoch: 2 | Batch Status: 46720/50000 (93%) | Loss: 1.877251
Train Epoch: 2 | Batch Status: 47360/50000 (95%) | Loss: 1.726788
Train Epoch: 2 | Batch Status: 48000/50000 (96%) | Loss: 1.728599
Train Epoch: 2 | Batch Status: 48640/50000 (97%) | Loss: 1.711790
Train Epoch: 2 | Batch Status: 49280/50000 (98%) | Loss: 1.540305
Train Epoch: 2 | Batch Status: 49920/50000 (100%) | Loss: 1.644948
Training time: 1m 27s
===========================
Test set: Average loss: 0.0282, Accuracy: 3229/10000 (32%)
Testing time: 1m 33s
Train Epoch: 3 | Batch Status: 0/50000 (0%) | Loss: 1.768116
Train Epoch: 3 | Batch Status: 640/50000 (1%) | Loss: 1.730283
Train Epoch: 3 | Batch Status: 1280/50000 (3%) | Loss: 1.686540
Train Epoch: 3 | Batch Status: 1920/50000 (4%) | Loss: 1.603000
Train Epoch: 3 | Batch Status: 2560/50000 (5%) | Loss: 1.896792
Train Epoch: 3 | Batch Status: 3200/50000 (6%) | Loss: 1.869055
Train Epoch: 3 | Batch Status: 3840/50000 (8%) | Loss: 1.773907
Train Epoch: 3 | Batch Status: 4480/50000 (9%) | Loss: 1.639561
Train Epoch: 3 | Batch Status: 5120/50000 (10%) | Loss: 1.702959
Train Epoch: 3 | Batch Status: 5760/50000 (12%) | Loss: 1.813359
Train Epoch: 3 | Batch Status: 6400/50000 (13%) | Loss: 1.910820
Train Epoch: 3 | Batch Status: 7040/50000 (14%) | Loss: 1.798847
Train Epoch: 3 | Batch Status: 7680/50000 (15%) | Loss: 1.538181
Train Epoch: 3 | Batch Status: 8320/50000 (17%) | Loss: 1.839124
Train Epoch: 3 | Batch Status: 8960/50000 (18%) | Loss: 1.491529
Train Epoch: 3 | Batch Status: 9600/50000 (19%) | Loss: 1.554667
Train Epoch: 3 | Batch Status: 10240/50000 (20%) | Loss: 1.565022
Train Epoch: 3 | Batch Status: 10880/50000 (22%) | Loss: 1.691890
Train Epoch: 3 | Batch Status: 11520/50000 (23%) | Loss: 1.716174
Train Epoch: 3 | Batch Status: 12160/50000 (24%) | Loss: 1.710697
Train Epoch: 3 | Batch Status: 12800/50000 (26%) | Loss: 1.863846
Train Epoch: 3 | Batch Status: 13440/50000 (27%) | Loss: 1.503847
Train Epoch: 3 | Batch Status: 14080/50000 (28%) | Loss: 1.694488
Train Epoch: 3 | Batch Status: 14720/50000 (29%) | Loss: 1.715901
Train Epoch: 3 | Batch Status: 15360/50000 (31%) | Loss: 1.849757
Train Epoch: 3 | Batch Status: 16000/50000 (32%) | Loss: 1.541423
Train Epoch: 3 | Batch Status: 16640/50000 (33%) | Loss: 1.761231
Train Epoch: 3 | Batch Status: 17280/50000 (35%) | Loss: 1.688032
Train Epoch: 3 | Batch Status: 17920/50000 (36%) | Loss: 1.595274
Train Epoch: 3 | Batch Status: 18560/50000 (37%) | Loss: 1.848230
Train Epoch: 3 | Batch Status: 19200/50000 (38%) | Loss: 1.761558
Train Epoch: 3 | Batch Status: 19840/50000 (40%) | Loss: 1.586842
Train Epoch: 3 | Batch Status: 20480/50000 (41%) | Loss: 1.909065
Train Epoch: 3 | Batch Status: 21120/50000 (42%) | Loss: 1.774920
Train Epoch: 3 | Batch Status: 21760/50000 (43%) | Loss: 1.517505
Train Epoch: 3 | Batch Status: 22400/50000 (45%) | Loss: 1.767535
Train Epoch: 3 | Batch Status: 23040/50000 (46%) | Loss: 1.920747
Train Epoch: 3 | Batch Status: 23680/50000 (47%) | Loss: 1.589665
Train Epoch: 3 | Batch Status: 24320/50000 (49%) | Loss: 1.572673
Train Epoch: 3 | Batch Status: 24960/50000 (50%) | Loss: 1.674892
Train Epoch: 3 | Batch Status: 25600/50000 (51%) | Loss: 1.707860
Train Epoch: 3 | Batch Status: 26240/50000 (52%) | Loss: 1.510449
Train Epoch: 3 | Batch Status: 26880/50000 (54%) | Loss: 1.639334
Train Epoch: 3 | Batch Status: 27520/50000 (55%) | Loss: 1.608330
Train Epoch: 3 | Batch Status: 28160/50000 (56%) | Loss: 1.770492
Train Epoch: 3 | Batch Status: 28800/50000 (58%) | Loss: 1.634850
Train Epoch: 3 | Batch Status: 29440/50000 (59%) | Loss: 1.845723
Train Epoch: 3 | Batch Status: 30080/50000 (60%) | Loss: 1.595461
Train Epoch: 3 | Batch Status: 30720/50000 (61%) | Loss: 1.618594
Train Epoch: 3 | Batch Status: 31360/50000 (63%) | Loss: 1.581645
Train Epoch: 3 | Batch Status: 32000/50000 (64%) | Loss: 1.665185
Train Epoch: 3 | Batch Status: 32640/50000 (65%) | Loss: 1.848985
Train Epoch: 3 | Batch Status: 33280/50000 (66%) | Loss: 1.669505
Train Epoch: 3 | Batch Status: 33920/50000 (68%) | Loss: 1.692372
Train Epoch: 3 | Batch Status: 34560/50000 (69%) | Loss: 1.401134
Train Epoch: 3 | Batch Status: 35200/50000 (70%) | Loss: 1.730937
Train Epoch: 3 | Batch Status: 35840/50000 (72%) | Loss: 1.586890
Train Epoch: 3 | Batch Status: 36480/50000 (73%) | Loss: 1.597723
Train Epoch: 3 | Batch Status: 37120/50000 (74%) | Loss: 1.825315
Train Epoch: 3 | Batch Status: 37760/50000 (75%) | Loss: 1.709872
Train Epoch: 3 | Batch Status: 38400/50000 (77%) | Loss: 1.663622
Train Epoch: 3 | Batch Status: 39040/50000 (78%) | Loss: 1.655113
Train Epoch: 3 | Batch Status: 39680/50000 (79%) | Loss: 1.653528
Train Epoch: 3 | Batch Status: 40320/50000 (81%) | Loss: 1.681132
Train Epoch: 3 | Batch Status: 40960/50000 (82%) | Loss: 1.889844
Train Epoch: 3 | Batch Status: 41600/50000 (83%) | Loss: 1.624373
Train Epoch: 3 | Batch Status: 42240/50000 (84%) | Loss: 1.595711
Train Epoch: 3 | Batch Status: 42880/50000 (86%) | Loss: 1.832262
Train Epoch: 3 | Batch Status: 43520/50000 (87%) | Loss: 1.518462
Train Epoch: 3 | Batch Status: 44160/50000 (88%) | Loss: 1.817246
Train Epoch: 3 | Batch Status: 44800/50000 (90%) | Loss: 1.675046
Train Epoch: 3 | Batch Status: 45440/50000 (91%) | Loss: 1.804441
Train Epoch: 3 | Batch Status: 46080/50000 (92%) | Loss: 1.613339
Train Epoch: 3 | Batch Status: 46720/50000 (93%) | Loss: 1.687828
Train Epoch: 3 | Batch Status: 47360/50000 (95%) | Loss: 1.866577
Train Epoch: 3 | Batch Status: 48000/50000 (96%) | Loss: 1.718022
Train Epoch: 3 | Batch Status: 48640/50000 (97%) | Loss: 1.521649
Train Epoch: 3 | Batch Status: 49280/50000 (98%) | Loss: 1.631775
Train Epoch: 3 | Batch Status: 49920/50000 (100%) | Loss: 1.665005
Training time: 1m 27s
===========================
Test set: Average loss: 0.0256, Accuracy: 4169/10000 (42%)
Testing time: 1m 33s
Train Epoch: 4 | Batch Status: 0/50000 (0%) | Loss: 1.677282
Train Epoch: 4 | Batch Status: 640/50000 (1%) | Loss: 1.513199
Train Epoch: 4 | Batch Status: 1280/50000 (3%) | Loss: 1.886015
Train Epoch: 4 | Batch Status: 1920/50000 (4%) | Loss: 1.540837
Train Epoch: 4 | Batch Status: 2560/50000 (5%) | Loss: 1.679512
Train Epoch: 4 | Batch Status: 3200/50000 (6%) | Loss: 1.582884
Train Epoch: 4 | Batch Status: 3840/50000 (8%) | Loss: 1.658608
Train Epoch: 4 | Batch Status: 4480/50000 (9%) | Loss: 1.642527
Train Epoch: 4 | Batch Status: 5120/50000 (10%) | Loss: 1.775126
Train Epoch: 4 | Batch Status: 5760/50000 (12%) | Loss: 1.744847
Train Epoch: 4 | Batch Status: 6400/50000 (13%) | Loss: 1.617718
Train Epoch: 4 | Batch Status: 7040/50000 (14%) | Loss: 1.537672
Train Epoch: 4 | Batch Status: 7680/50000 (15%) | Loss: 1.618605
Train Epoch: 4 | Batch Status: 8320/50000 (17%) | Loss: 1.599895
Train Epoch: 4 | Batch Status: 8960/50000 (18%) | Loss: 1.264695
Train Epoch: 4 | Batch Status: 9600/50000 (19%) | Loss: 1.682063
Train Epoch: 4 | Batch Status: 10240/50000 (20%) | Loss: 1.820005
Train Epoch: 4 | Batch Status: 10880/50000 (22%) | Loss: 1.582724
Train Epoch: 4 | Batch Status: 11520/50000 (23%) | Loss: 1.718227
Train Epoch: 4 | Batch Status: 12160/50000 (24%) | Loss: 1.646474
Train Epoch: 4 | Batch Status: 12800/50000 (26%) | Loss: 1.600295
Train Epoch: 4 | Batch Status: 13440/50000 (27%) | Loss: 1.498832
Train Epoch: 4 | Batch Status: 14080/50000 (28%) | Loss: 1.573980
Train Epoch: 4 | Batch Status: 14720/50000 (29%) | Loss: 1.436398
Train Epoch: 4 | Batch Status: 15360/50000 (31%) | Loss: 1.656486
Train Epoch: 4 | Batch Status: 16000/50000 (32%) | Loss: 1.514614
Train Epoch: 4 | Batch Status: 16640/50000 (33%) | Loss: 1.549209
Train Epoch: 4 | Batch Status: 17280/50000 (35%) | Loss: 1.644499
Train Epoch: 4 | Batch Status: 17920/50000 (36%) | Loss: 1.759935
Train Epoch: 4 | Batch Status: 18560/50000 (37%) | Loss: 1.933579
Train Epoch: 4 | Batch Status: 19200/50000 (38%) | Loss: 1.410463
Train Epoch: 4 | Batch Status: 19840/50000 (40%) | Loss: 1.826471
Train Epoch: 4 | Batch Status: 20480/50000 (41%) | Loss: 1.845950
Train Epoch: 4 | Batch Status: 21120/50000 (42%) | Loss: 1.616593
Train Epoch: 4 | Batch Status: 21760/50000 (43%) | Loss: 1.418246
Train Epoch: 4 | Batch Status: 22400/50000 (45%) | Loss: 1.675911
Train Epoch: 4 | Batch Status: 23040/50000 (46%) | Loss: 1.501991
Train Epoch: 4 | Batch Status: 23680/50000 (47%) | Loss: 1.522664
Train Epoch: 4 | Batch Status: 24320/50000 (49%) | Loss: 1.641462
Train Epoch: 4 | Batch Status: 24960/50000 (50%) | Loss: 1.535807
Train Epoch: 4 | Batch Status: 25600/50000 (51%) | Loss: 1.545786
Train Epoch: 4 | Batch Status: 26240/50000 (52%) | Loss: 1.736376
Train Epoch: 4 | Batch Status: 26880/50000 (54%) | Loss: 1.493565
Train Epoch: 4 | Batch Status: 27520/50000 (55%) | Loss: 1.469715
Train Epoch: 4 | Batch Status: 28160/50000 (56%) | Loss: 1.744099
Train Epoch: 4 | Batch Status: 28800/50000 (58%) | Loss: 1.534203
Train Epoch: 4 | Batch Status: 29440/50000 (59%) | Loss: 1.511301
Train Epoch: 4 | Batch Status: 30080/50000 (60%) | Loss: 1.678167
Train Epoch: 4 | Batch Status: 30720/50000 (61%) | Loss: 1.507967
Train Epoch: 4 | Batch Status: 31360/50000 (63%) | Loss: 1.506257
Train Epoch: 4 | Batch Status: 32000/50000 (64%) | Loss: 1.553823
Train Epoch: 4 | Batch Status: 32640/50000 (65%) | Loss: 1.777257
Train Epoch: 4 | Batch Status: 33280/50000 (66%) | Loss: 1.779165
Train Epoch: 4 | Batch Status: 33920/50000 (68%) | Loss: 1.495063
Train Epoch: 4 | Batch Status: 34560/50000 (69%) | Loss: 1.581740
Train Epoch: 4 | Batch Status: 35200/50000 (70%) | Loss: 1.548907
Train Epoch: 4 | Batch Status: 35840/50000 (72%) | Loss: 1.693789
Train Epoch: 4 | Batch Status: 36480/50000 (73%) | Loss: 1.406621
Train Epoch: 4 | Batch Status: 37120/50000 (74%) | Loss: 1.404296
Train Epoch: 4 | Batch Status: 37760/50000 (75%) | Loss: 1.500271
Train Epoch: 4 | Batch Status: 38400/50000 (77%) | Loss: 1.458206
Train Epoch: 4 | Batch Status: 39040/50000 (78%) | Loss: 1.681820
Train Epoch: 4 | Batch Status: 39680/50000 (79%) | Loss: 1.665606
Train Epoch: 4 | Batch Status: 40320/50000 (81%) | Loss: 1.467190
Train Epoch: 4 | Batch Status: 40960/50000 (82%) | Loss: 1.599778
Train Epoch: 4 | Batch Status: 41600/50000 (83%) | Loss: 1.480560
Train Epoch: 4 | Batch Status: 42240/50000 (84%) | Loss: 1.428285
Train Epoch: 4 | Batch Status: 42880/50000 (86%) | Loss: 1.674890
Train Epoch: 4 | Batch Status: 43520/50000 (87%) | Loss: 1.654979
Train Epoch: 4 | Batch Status: 44160/50000 (88%) | Loss: 1.700013
Train Epoch: 4 | Batch Status: 44800/50000 (90%) | Loss: 1.771815
Train Epoch: 4 | Batch Status: 45440/50000 (91%) | Loss: 1.551549
Train Epoch: 4 | Batch Status: 46080/50000 (92%) | Loss: 1.451054
Train Epoch: 4 | Batch Status: 46720/50000 (93%) | Loss: 1.618992
Train Epoch: 4 | Batch Status: 47360/50000 (95%) | Loss: 1.718344
Train Epoch: 4 | Batch Status: 48000/50000 (96%) | Loss: 1.381191
Train Epoch: 4 | Batch Status: 48640/50000 (97%) | Loss: 1.388604
Train Epoch: 4 | Batch Status: 49280/50000 (98%) | Loss: 1.314847
Train Epoch: 4 | Batch Status: 49920/50000 (100%) | Loss: 1.574936
Training time: 1m 28s
===========================
Test set: Average loss: 0.0265, Accuracy: 3945/10000 (39%)
Testing time: 1m 34s
Train Epoch: 5 | Batch Status: 0/50000 (0%) | Loss: 1.605555
Train Epoch: 5 | Batch Status: 640/50000 (1%) | Loss: 1.455946
Train Epoch: 5 | Batch Status: 1280/50000 (3%) | Loss: 1.410821
Train Epoch: 5 | Batch Status: 1920/50000 (4%) | Loss: 1.538270
Train Epoch: 5 | Batch Status: 2560/50000 (5%) | Loss: 1.653059
Train Epoch: 5 | Batch Status: 3200/50000 (6%) | Loss: 1.578912
Train Epoch: 5 | Batch Status: 3840/50000 (8%) | Loss: 1.756927
Train Epoch: 5 | Batch Status: 4480/50000 (9%) | Loss: 1.602512
Train Epoch: 5 | Batch Status: 5120/50000 (10%) | Loss: 1.434900
Train Epoch: 5 | Batch Status: 5760/50000 (12%) | Loss: 1.505043
Train Epoch: 5 | Batch Status: 6400/50000 (13%) | Loss: 1.404257
Train Epoch: 5 | Batch Status: 7040/50000 (14%) | Loss: 1.477917
Train Epoch: 5 | Batch Status: 7680/50000 (15%) | Loss: 1.589346
Train Epoch: 5 | Batch Status: 8320/50000 (17%) | Loss: 1.429876
Train Epoch: 5 | Batch Status: 8960/50000 (18%) | Loss: 1.506817
Train Epoch: 5 | Batch Status: 9600/50000 (19%) | Loss: 1.486432
Train Epoch: 5 | Batch Status: 10240/50000 (20%) | Loss: 1.553505
Train Epoch: 5 | Batch Status: 10880/50000 (22%) | Loss: 1.588868
Train Epoch: 5 | Batch Status: 11520/50000 (23%) | Loss: 1.358062
Train Epoch: 5 | Batch Status: 12160/50000 (24%) | Loss: 1.259551
Train Epoch: 5 | Batch Status: 12800/50000 (26%) | Loss: 1.523040
Train Epoch: 5 | Batch Status: 13440/50000 (27%) | Loss: 1.399446
Train Epoch: 5 | Batch Status: 14080/50000 (28%) | Loss: 1.597720
Train Epoch: 5 | Batch Status: 14720/50000 (29%) | Loss: 1.370868
Train Epoch: 5 | Batch Status: 15360/50000 (31%) | Loss: 1.524670
Train Epoch: 5 | Batch Status: 16000/50000 (32%) | Loss: 1.352793
Train Epoch: 5 | Batch Status: 16640/50000 (33%) | Loss: 1.634609
Train Epoch: 5 | Batch Status: 17280/50000 (35%) | Loss: 1.417049
Train Epoch: 5 | Batch Status: 17920/50000 (36%) | Loss: 1.752507
Train Epoch: 5 | Batch Status: 18560/50000 (37%) | Loss: 1.678107
Train Epoch: 5 | Batch Status: 19200/50000 (38%) | Loss: 1.679064
Train Epoch: 5 | Batch Status: 19840/50000 (40%) | Loss: 1.727497
Train Epoch: 5 | Batch Status: 20480/50000 (41%) | Loss: 1.360547
Train Epoch: 5 | Batch Status: 21120/50000 (42%) | Loss: 1.410406
Train Epoch: 5 | Batch Status: 21760/50000 (43%) | Loss: 1.703155
Train Epoch: 5 | Batch Status: 22400/50000 (45%) | Loss: 1.504737
Train Epoch: 5 | Batch Status: 23040/50000 (46%) | Loss: 1.461484
Train Epoch: 5 | Batch Status: 23680/50000 (47%) | Loss: 1.427690
Train Epoch: 5 | Batch Status: 24320/50000 (49%) | Loss: 1.535331
Train Epoch: 5 | Batch Status: 24960/50000 (50%) | Loss: 1.463099
Train Epoch: 5 | Batch Status: 25600/50000 (51%) | Loss: 1.872200
Train Epoch: 5 | Batch Status: 26240/50000 (52%) | Loss: 1.589828
Train Epoch: 5 | Batch Status: 26880/50000 (54%) | Loss: 1.423685
Train Epoch: 5 | Batch Status: 27520/50000 (55%) | Loss: 1.432009
Train Epoch: 5 | Batch Status: 28160/50000 (56%) | Loss: 1.479521
Train Epoch: 5 | Batch Status: 28800/50000 (58%) | Loss: 1.704886
Train Epoch: 5 | Batch Status: 29440/50000 (59%) | Loss: 1.558359
Train Epoch: 5 | Batch Status: 30080/50000 (60%) | Loss: 1.519752
Train Epoch: 5 | Batch Status: 30720/50000 (61%) | Loss: 1.469313
Train Epoch: 5 | Batch Status: 31360/50000 (63%) | Loss: 1.500289
Train Epoch: 5 | Batch Status: 32000/50000 (64%) | Loss: 1.489048
Train Epoch: 5 | Batch Status: 32640/50000 (65%) | Loss: 1.516937
Train Epoch: 5 | Batch Status: 33280/50000 (66%) | Loss: 1.479420
Train Epoch: 5 | Batch Status: 33920/50000 (68%) | Loss: 1.576373
Train Epoch: 5 | Batch Status: 34560/50000 (69%) | Loss: 1.436560
Train Epoch: 5 | Batch Status: 35200/50000 (70%) | Loss: 1.538372
Train Epoch: 5 | Batch Status: 35840/50000 (72%) | Loss: 1.474741
Train Epoch: 5 | Batch Status: 36480/50000 (73%) | Loss: 1.466787
Train Epoch: 5 | Batch Status: 37120/50000 (74%) | Loss: 1.436701
Train Epoch: 5 | Batch Status: 37760/50000 (75%) | Loss: 1.529624
Train Epoch: 5 | Batch Status: 38400/50000 (77%) | Loss: 1.723087
Train Epoch: 5 | Batch Status: 39040/50000 (78%) | Loss: 1.336789
Train Epoch: 5 | Batch Status: 39680/50000 (79%) | Loss: 1.218106
Train Epoch: 5 | Batch Status: 40320/50000 (81%) | Loss: 1.626625
Train Epoch: 5 | Batch Status: 40960/50000 (82%) | Loss: 1.596893
Train Epoch: 5 | Batch Status: 41600/50000 (83%) | Loss: 1.449440
Train Epoch: 5 | Batch Status: 42240/50000 (84%) | Loss: 1.682071
Train Epoch: 5 | Batch Status: 42880/50000 (86%) | Loss: 1.640857
Train Epoch: 5 | Batch Status: 43520/50000 (87%) | Loss: 1.430601
Train Epoch: 5 | Batch Status: 44160/50000 (88%) | Loss: 1.549150
Train Epoch: 5 | Batch Status: 44800/50000 (90%) | Loss: 1.566269
Train Epoch: 5 | Batch Status: 45440/50000 (91%) | Loss: 1.672719
Train Epoch: 5 | Batch Status: 46080/50000 (92%) | Loss: 1.273215
Train Epoch: 5 | Batch Status: 46720/50000 (93%) | Loss: 1.444584
Train Epoch: 5 | Batch Status: 47360/50000 (95%) | Loss: 1.531994
Train Epoch: 5 | Batch Status: 48000/50000 (96%) | Loss: 1.456935
Train Epoch: 5 | Batch Status: 48640/50000 (97%) | Loss: 1.581073
Train Epoch: 5 | Batch Status: 49280/50000 (98%) | Loss: 1.391919
Train Epoch: 5 | Batch Status: 49920/50000 (100%) | Loss: 1.326878
Training time: 1m 27s
===========================
Test set: Average loss: 0.0246, Accuracy: 4350/10000 (44%)
Testing time: 1m 33s
Train Epoch: 6 | Batch Status: 0/50000 (0%) | Loss: 1.442830
Train Epoch: 6 | Batch Status: 640/50000 (1%) | Loss: 1.547090
Train Epoch: 6 | Batch Status: 1280/50000 (3%) | Loss: 1.571403
Train Epoch: 6 | Batch Status: 1920/50000 (4%) | Loss: 1.494079
Train Epoch: 6 | Batch Status: 2560/50000 (5%) | Loss: 1.455932
Train Epoch: 6 | Batch Status: 3200/50000 (6%) | Loss: 1.370356
Train Epoch: 6 | Batch Status: 3840/50000 (8%) | Loss: 1.240431
Train Epoch: 6 | Batch Status: 4480/50000 (9%) | Loss: 1.559212
Train Epoch: 6 | Batch Status: 5120/50000 (10%) | Loss: 1.664791
Train Epoch: 6 | Batch Status: 5760/50000 (12%) | Loss: 1.333900
Train Epoch: 6 | Batch Status: 6400/50000 (13%) | Loss: 1.443158
Train Epoch: 6 | Batch Status: 7040/50000 (14%) | Loss: 1.454577
Train Epoch: 6 | Batch Status: 7680/50000 (15%) | Loss: 1.508080
Train Epoch: 6 | Batch Status: 8320/50000 (17%) | Loss: 1.342720
Train Epoch: 6 | Batch Status: 8960/50000 (18%) | Loss: 1.511607
Train Epoch: 6 | Batch Status: 9600/50000 (19%) | Loss: 1.382897
Train Epoch: 6 | Batch Status: 10240/50000 (20%) | Loss: 1.387063
Train Epoch: 6 | Batch Status: 10880/50000 (22%) | Loss: 1.511363
Train Epoch: 6 | Batch Status: 11520/50000 (23%) | Loss: 1.589361
Train Epoch: 6 | Batch Status: 12160/50000 (24%) | Loss: 1.585533
Train Epoch: 6 | Batch Status: 12800/50000 (26%) | Loss: 1.788427
Train Epoch: 6 | Batch Status: 13440/50000 (27%) | Loss: 1.730775
Train Epoch: 6 | Batch Status: 14080/50000 (28%) | Loss: 1.431499
Train Epoch: 6 | Batch Status: 14720/50000 (29%) | Loss: 1.465995
Train Epoch: 6 | Batch Status: 15360/50000 (31%) | Loss: 1.551904
Train Epoch: 6 | Batch Status: 16000/50000 (32%) | Loss: 1.599135
Train Epoch: 6 | Batch Status: 16640/50000 (33%) | Loss: 1.560427
Train Epoch: 6 | Batch Status: 17280/50000 (35%) | Loss: 1.541293
Train Epoch: 6 | Batch Status: 17920/50000 (36%) | Loss: 1.714550
Train Epoch: 6 | Batch Status: 18560/50000 (37%) | Loss: 1.485717
Train Epoch: 6 | Batch Status: 19200/50000 (38%) | Loss: 1.654223
Train Epoch: 6 | Batch Status: 19840/50000 (40%) | Loss: 1.537867
Train Epoch: 6 | Batch Status: 20480/50000 (41%) | Loss: 1.306252
Train Epoch: 6 | Batch Status: 21120/50000 (42%) | Loss: 1.414868
Train Epoch: 6 | Batch Status: 21760/50000 (43%) | Loss: 1.515314
Train Epoch: 6 | Batch Status: 22400/50000 (45%) | Loss: 1.758172
Train Epoch: 6 | Batch Status: 23040/50000 (46%) | Loss: 1.329770
Train Epoch: 6 | Batch Status: 23680/50000 (47%) | Loss: 1.315385
Train Epoch: 6 | Batch Status: 24320/50000 (49%) | Loss: 1.398068
Train Epoch: 6 | Batch Status: 24960/50000 (50%) | Loss: 1.569431
Train Epoch: 6 | Batch Status: 25600/50000 (51%) | Loss: 1.650755
Train Epoch: 6 | Batch Status: 26240/50000 (52%) | Loss: 1.480043
Train Epoch: 6 | Batch Status: 26880/50000 (54%) | Loss: 1.546058
Train Epoch: 6 | Batch Status: 27520/50000 (55%) | Loss: 1.446811
Train Epoch: 6 | Batch Status: 28160/50000 (56%) | Loss: 1.529022
Train Epoch: 6 | Batch Status: 28800/50000 (58%) | Loss: 1.377270
Train Epoch: 6 | Batch Status: 29440/50000 (59%) | Loss: 1.615380
Train Epoch: 6 | Batch Status: 30080/50000 (60%) | Loss: 1.570226
Train Epoch: 6 | Batch Status: 30720/50000 (61%) | Loss: 1.399658
Train Epoch: 6 | Batch Status: 31360/50000 (63%) | Loss: 1.243811
Train Epoch: 6 | Batch Status: 32000/50000 (64%) | Loss: 1.560842
Train Epoch: 6 | Batch Status: 32640/50000 (65%) | Loss: 1.598462
Train Epoch: 6 | Batch Status: 33280/50000 (66%) | Loss: 1.146867
Train Epoch: 6 | Batch Status: 33920/50000 (68%) | Loss: 1.634141
Train Epoch: 6 | Batch Status: 34560/50000 (69%) | Loss: 1.219320
Train Epoch: 6 | Batch Status: 35200/50000 (70%) | Loss: 1.287849
Train Epoch: 6 | Batch Status: 35840/50000 (72%) | Loss: 1.260936
Train Epoch: 6 | Batch Status: 36480/50000 (73%) | Loss: 1.544801
Train Epoch: 6 | Batch Status: 37120/50000 (74%) | Loss: 1.431138
Train Epoch: 6 | Batch Status: 37760/50000 (75%) | Loss: 1.447309
Train Epoch: 6 | Batch Status: 38400/50000 (77%) | Loss: 1.546222
Train Epoch: 6 | Batch Status: 39040/50000 (78%) | Loss: 1.188765
Train Epoch: 6 | Batch Status: 39680/50000 (79%) | Loss: 1.425805
Train Epoch: 6 | Batch Status: 40320/50000 (81%) | Loss: 1.446874
Train Epoch: 6 | Batch Status: 40960/50000 (82%) | Loss: 1.444780
Train Epoch: 6 | Batch Status: 41600/50000 (83%) | Loss: 1.429351
Train Epoch: 6 | Batch Status: 42240/50000 (84%) | Loss: 1.486021
Train Epoch: 6 | Batch Status: 42880/50000 (86%) | Loss: 1.782387
Train Epoch: 6 | Batch Status: 43520/50000 (87%) | Loss: 1.403029
Train Epoch: 6 | Batch Status: 44160/50000 (88%) | Loss: 1.740201
Train Epoch: 6 | Batch Status: 44800/50000 (90%) | Loss: 1.561266
Train Epoch: 6 | Batch Status: 45440/50000 (91%) | Loss: 1.254946
Train Epoch: 6 | Batch Status: 46080/50000 (92%) | Loss: 1.594063
Train Epoch: 6 | Batch Status: 46720/50000 (93%) | Loss: 1.464519
Train Epoch: 6 | Batch Status: 47360/50000 (95%) | Loss: 1.525297
Train Epoch: 6 | Batch Status: 48000/50000 (96%) | Loss: 1.500082
Train Epoch: 6 | Batch Status: 48640/50000 (97%) | Loss: 1.622764
Train Epoch: 6 | Batch Status: 49280/50000 (98%) | Loss: 1.622441
Train Epoch: 6 | Batch Status: 49920/50000 (100%) | Loss: 1.438899
Training time: 1m 27s
===========================
Test set: Average loss: 0.0237, Accuracy: 4503/10000 (45%)
Testing time: 1m 33s
Train Epoch: 7 | Batch Status: 0/50000 (0%) | Loss: 1.310195
Train Epoch: 7 | Batch Status: 640/50000 (1%) | Loss: 1.362983
Train Epoch: 7 | Batch Status: 1280/50000 (3%) | Loss: 1.427926
Train Epoch: 7 | Batch Status: 1920/50000 (4%) | Loss: 1.344684
Train Epoch: 7 | Batch Status: 2560/50000 (5%) | Loss: 1.544402
Train Epoch: 7 | Batch Status: 3200/50000 (6%) | Loss: 1.338373
Train Epoch: 7 | Batch Status: 3840/50000 (8%) | Loss: 1.264085
Train Epoch: 7 | Batch Status: 4480/50000 (9%) | Loss: 1.419212
Train Epoch: 7 | Batch Status: 5120/50000 (10%) | Loss: 1.409555
Train Epoch: 7 | Batch Status: 5760/50000 (12%) | Loss: 1.530289
Train Epoch: 7 | Batch Status: 6400/50000 (13%) | Loss: 1.167715
Train Epoch: 7 | Batch Status: 7040/50000 (14%) | Loss: 1.230759
Train Epoch: 7 | Batch Status: 7680/50000 (15%) | Loss: 1.269284
Train Epoch: 7 | Batch Status: 8320/50000 (17%) | Loss: 1.292635
Train Epoch: 7 | Batch Status: 8960/50000 (18%) | Loss: 1.368779
Train Epoch: 7 | Batch Status: 9600/50000 (19%) | Loss: 1.562687
Train Epoch: 7 | Batch Status: 10240/50000 (20%) | Loss: 1.326652
Train Epoch: 7 | Batch Status: 10880/50000 (22%) | Loss: 1.479441
Train Epoch: 7 | Batch Status: 11520/50000 (23%) | Loss: 1.366899
Train Epoch: 7 | Batch Status: 12160/50000 (24%) | Loss: 1.442387
Train Epoch: 7 | Batch Status: 12800/50000 (26%) | Loss: 1.539716
Train Epoch: 7 | Batch Status: 13440/50000 (27%) | Loss: 1.288757
Train Epoch: 7 | Batch Status: 14080/50000 (28%) | Loss: 1.252488
Train Epoch: 7 | Batch Status: 14720/50000 (29%) | Loss: 1.661288
Train Epoch: 7 | Batch Status: 15360/50000 (31%) | Loss: 1.453416
Train Epoch: 7 | Batch Status: 16000/50000 (32%) | Loss: 1.382672
Train Epoch: 7 | Batch Status: 16640/50000 (33%) | Loss: 1.428522
Train Epoch: 7 | Batch Status: 17280/50000 (35%) | Loss: 1.379897
Train Epoch: 7 | Batch Status: 17920/50000 (36%) | Loss: 1.599552
Train Epoch: 7 | Batch Status: 18560/50000 (37%) | Loss: 1.555270
Train Epoch: 7 | Batch Status: 19200/50000 (38%) | Loss: 1.616063
Train Epoch: 7 | Batch Status: 19840/50000 (40%) | Loss: 1.320260
Train Epoch: 7 | Batch Status: 20480/50000 (41%) | Loss: 1.264514
Train Epoch: 7 | Batch Status: 21120/50000 (42%) | Loss: 1.379204
Train Epoch: 7 | Batch Status: 21760/50000 (43%) | Loss: 1.485392
Train Epoch: 7 | Batch Status: 22400/50000 (45%) | Loss: 1.488723
Train Epoch: 7 | Batch Status: 23040/50000 (46%) | Loss: 1.470069
Train Epoch: 7 | Batch Status: 23680/50000 (47%) | Loss: 1.649116
Train Epoch: 7 | Batch Status: 24320/50000 (49%) | Loss: 1.301881
Train Epoch: 7 | Batch Status: 24960/50000 (50%) | Loss: 1.456809
Train Epoch: 7 | Batch Status: 25600/50000 (51%) | Loss: 1.285135
Train Epoch: 7 | Batch Status: 26240/50000 (52%) | Loss: 1.419113
Train Epoch: 7 | Batch Status: 26880/50000 (54%) | Loss: 1.427812
Train Epoch: 7 | Batch Status: 27520/50000 (55%) | Loss: 1.415956
Train Epoch: 7 | Batch Status: 28160/50000 (56%) | Loss: 1.360389
Train Epoch: 7 | Batch Status: 28800/50000 (58%) | Loss: 1.200817
Train Epoch: 7 | Batch Status: 29440/50000 (59%) | Loss: 1.410831
Train Epoch: 7 | Batch Status: 30080/50000 (60%) | Loss: 1.623620
Train Epoch: 7 | Batch Status: 30720/50000 (61%) | Loss: 1.489586
Train Epoch: 7 | Batch Status: 31360/50000 (63%) | Loss: 1.077634
Train Epoch: 7 | Batch Status: 32000/50000 (64%) | Loss: 1.486202
Train Epoch: 7 | Batch Status: 32640/50000 (65%) | Loss: 1.397686
Train Epoch: 7 | Batch Status: 33280/50000 (66%) | Loss: 1.619339
Train Epoch: 7 | Batch Status: 33920/50000 (68%) | Loss: 1.463072
Train Epoch: 7 | Batch Status: 34560/50000 (69%) | Loss: 1.278601
Train Epoch: 7 | Batch Status: 35200/50000 (70%) | Loss: 1.521398
Train Epoch: 7 | Batch Status: 35840/50000 (72%) | Loss: 1.314894
Train Epoch: 7 | Batch Status: 36480/50000 (73%) | Loss: 1.304918
Train Epoch: 7 | Batch Status: 37120/50000 (74%) | Loss: 1.441467
Train Epoch: 7 | Batch Status: 37760/50000 (75%) | Loss: 1.248838
Train Epoch: 7 | Batch Status: 38400/50000 (77%) | Loss: 1.293975
Train Epoch: 7 | Batch Status: 39040/50000 (78%) | Loss: 1.363202
Train Epoch: 7 | Batch Status: 39680/50000 (79%) | Loss: 1.718161
Train Epoch: 7 | Batch Status: 40320/50000 (81%) | Loss: 1.520401
Train Epoch: 7 | Batch Status: 40960/50000 (82%) | Loss: 1.360018
Train Epoch: 7 | Batch Status: 41600/50000 (83%) | Loss: 1.415223
Train Epoch: 7 | Batch Status: 42240/50000 (84%) | Loss: 1.252342
Train Epoch: 7 | Batch Status: 42880/50000 (86%) | Loss: 1.220743
Train Epoch: 7 | Batch Status: 43520/50000 (87%) | Loss: 1.462478
Train Epoch: 7 | Batch Status: 44160/50000 (88%) | Loss: 1.258500
Train Epoch: 7 | Batch Status: 44800/50000 (90%) | Loss: 1.623188
Train Epoch: 7 | Batch Status: 45440/50000 (91%) | Loss: 1.719346
Train Epoch: 7 | Batch Status: 46080/50000 (92%) | Loss: 1.480481
Train Epoch: 7 | Batch Status: 46720/50000 (93%) | Loss: 1.560724
Train Epoch: 7 | Batch Status: 47360/50000 (95%) | Loss: 1.105265
Train Epoch: 7 | Batch Status: 48000/50000 (96%) | Loss: 1.500532
Train Epoch: 7 | Batch Status: 48640/50000 (97%) | Loss: 1.475235
Train Epoch: 7 | Batch Status: 49280/50000 (98%) | Loss: 1.585122
Train Epoch: 7 | Batch Status: 49920/50000 (100%) | Loss: 1.237115
Training time: 1m 27s
===========================
Test set: Average loss: 0.0228, Accuracy: 4841/10000 (48%)
Testing time: 1m 33s
Train Epoch: 8 | Batch Status: 0/50000 (0%) | Loss: 1.490749
Train Epoch: 8 | Batch Status: 640/50000 (1%) | Loss: 1.398444
Train Epoch: 8 | Batch Status: 1280/50000 (3%) | Loss: 1.188814
Train Epoch: 8 | Batch Status: 1920/50000 (4%) | Loss: 1.303728
Train Epoch: 8 | Batch Status: 2560/50000 (5%) | Loss: 1.237250
Train Epoch: 8 | Batch Status: 3200/50000 (6%) | Loss: 1.382255
Train Epoch: 8 | Batch Status: 3840/50000 (8%) | Loss: 1.311844
Train Epoch: 8 | Batch Status: 4480/50000 (9%) | Loss: 1.342394
Train Epoch: 8 | Batch Status: 5120/50000 (10%) | Loss: 1.497441
Train Epoch: 8 | Batch Status: 5760/50000 (12%) | Loss: 1.855448
Train Epoch: 8 | Batch Status: 6400/50000 (13%) | Loss: 1.517682
Train Epoch: 8 | Batch Status: 7040/50000 (14%) | Loss: 1.414869
Train Epoch: 8 | Batch Status: 7680/50000 (15%) | Loss: 1.241558
Train Epoch: 8 | Batch Status: 8320/50000 (17%) | Loss: 1.602004
Train Epoch: 8 | Batch Status: 8960/50000 (18%) | Loss: 1.488796
Train Epoch: 8 | Batch Status: 9600/50000 (19%) | Loss: 1.412927
Train Epoch: 8 | Batch Status: 10240/50000 (20%) | Loss: 1.700195
Train Epoch: 8 | Batch Status: 10880/50000 (22%) | Loss: 1.852889
Train Epoch: 8 | Batch Status: 11520/50000 (23%) | Loss: 1.505501
Train Epoch: 8 | Batch Status: 12160/50000 (24%) | Loss: 1.285174
Train Epoch: 8 | Batch Status: 12800/50000 (26%) | Loss: 1.439385
Train Epoch: 8 | Batch Status: 13440/50000 (27%) | Loss: 1.446339
Train Epoch: 8 | Batch Status: 14080/50000 (28%) | Loss: 1.352607
Train Epoch: 8 | Batch Status: 14720/50000 (29%) | Loss: 1.464090
Train Epoch: 8 | Batch Status: 15360/50000 (31%) | Loss: 1.273401
Train Epoch: 8 | Batch Status: 16000/50000 (32%) | Loss: 1.536160
Train Epoch: 8 | Batch Status: 16640/50000 (33%) | Loss: 1.348355
Train Epoch: 8 | Batch Status: 17280/50000 (35%) | Loss: 1.325414
Train Epoch: 8 | Batch Status: 17920/50000 (36%) | Loss: 1.611929
Train Epoch: 8 | Batch Status: 18560/50000 (37%) | Loss: 1.279288
Train Epoch: 8 | Batch Status: 19200/50000 (38%) | Loss: 1.649172
Train Epoch: 8 | Batch Status: 19840/50000 (40%) | Loss: 1.221668
Train Epoch: 8 | Batch Status: 20480/50000 (41%) | Loss: 1.578316
Train Epoch: 8 | Batch Status: 21120/50000 (42%) | Loss: 1.367952
Train Epoch: 8 | Batch Status: 21760/50000 (43%) | Loss: 1.364442
Train Epoch: 8 | Batch Status: 22400/50000 (45%) | Loss: 1.296115
Train Epoch: 8 | Batch Status: 23040/50000 (46%) | Loss: 1.380327
Train Epoch: 8 | Batch Status: 23680/50000 (47%) | Loss: 1.203148
Train Epoch: 8 | Batch Status: 24320/50000 (49%) | Loss: 1.156127
Train Epoch: 8 | Batch Status: 24960/50000 (50%) | Loss: 1.313798
Train Epoch: 8 | Batch Status: 25600/50000 (51%) | Loss: 1.300853
Train Epoch: 8 | Batch Status: 26240/50000 (52%) | Loss: 1.536026
Train Epoch: 8 | Batch Status: 26880/50000 (54%) | Loss: 1.320392
Train Epoch: 8 | Batch Status: 27520/50000 (55%) | Loss: 1.392608
Train Epoch: 8 | Batch Status: 28160/50000 (56%) | Loss: 1.437314
Train Epoch: 8 | Batch Status: 28800/50000 (58%) | Loss: 1.307963
Train Epoch: 8 | Batch Status: 29440/50000 (59%) | Loss: 1.461182
Train Epoch: 8 | Batch Status: 30080/50000 (60%) | Loss: 1.501713
Train Epoch: 8 | Batch Status: 30720/50000 (61%) | Loss: 1.216869
Train Epoch: 8 | Batch Status: 31360/50000 (63%) | Loss: 1.184639
Train Epoch: 8 | Batch Status: 32000/50000 (64%) | Loss: 1.316712
Train Epoch: 8 | Batch Status: 32640/50000 (65%) | Loss: 1.489544
Train Epoch: 8 | Batch Status: 33280/50000 (66%) | Loss: 1.353706
Train Epoch: 8 | Batch Status: 33920/50000 (68%) | Loss: 1.565584
Train Epoch: 8 | Batch Status: 34560/50000 (69%) | Loss: 1.526959
Train Epoch: 8 | Batch Status: 35200/50000 (70%) | Loss: 1.361673
Train Epoch: 8 | Batch Status: 35840/50000 (72%) | Loss: 1.596369
Train Epoch: 8 | Batch Status: 36480/50000 (73%) | Loss: 1.318618
Train Epoch: 8 | Batch Status: 37120/50000 (74%) | Loss: 1.742510
Train Epoch: 8 | Batch Status: 37760/50000 (75%) | Loss: 1.492133
Train Epoch: 8 | Batch Status: 38400/50000 (77%) | Loss: 1.650508
Train Epoch: 8 | Batch Status: 39040/50000 (78%) | Loss: 1.338959
Train Epoch: 8 | Batch Status: 39680/50000 (79%) | Loss: 1.418240
Train Epoch: 8 | Batch Status: 40320/50000 (81%) | Loss: 1.451600
Train Epoch: 8 | Batch Status: 40960/50000 (82%) | Loss: 1.616524
Train Epoch: 8 | Batch Status: 41600/50000 (83%) | Loss: 1.427878
Train Epoch: 8 | Batch Status: 42240/50000 (84%) | Loss: 1.211004
Train Epoch: 8 | Batch Status: 42880/50000 (86%) | Loss: 1.404809
Train Epoch: 8 | Batch Status: 43520/50000 (87%) | Loss: 1.513769
Train Epoch: 8 | Batch Status: 44160/50000 (88%) | Loss: 1.380162
Train Epoch: 8 | Batch Status: 44800/50000 (90%) | Loss: 1.406452
Train Epoch: 8 | Batch Status: 45440/50000 (91%) | Loss: 1.336924
Train Epoch: 8 | Batch Status: 46080/50000 (92%) | Loss: 1.512568
Train Epoch: 8 | Batch Status: 46720/50000 (93%) | Loss: 1.488394
Train Epoch: 8 | Batch Status: 47360/50000 (95%) | Loss: 1.448325
Train Epoch: 8 | Batch Status: 48000/50000 (96%) | Loss: 1.250934
Train Epoch: 8 | Batch Status: 48640/50000 (97%) | Loss: 1.425794
Train Epoch: 8 | Batch Status: 49280/50000 (98%) | Loss: 1.589084
Train Epoch: 8 | Batch Status: 49920/50000 (100%) | Loss: 1.378270
Training time: 1m 28s
===========================
Test set: Average loss: 0.0240, Accuracy: 4488/10000 (45%)
Testing time: 1m 34s
Train Epoch: 9 | Batch Status: 0/50000 (0%) | Loss: 1.138981
Train Epoch: 9 | Batch Status: 640/50000 (1%) | Loss: 1.377318
Train Epoch: 9 | Batch Status: 1280/50000 (3%) | Loss: 1.253896
Train Epoch: 9 | Batch Status: 1920/50000 (4%) | Loss: 1.470333
Train Epoch: 9 | Batch Status: 2560/50000 (5%) | Loss: 1.274425
Train Epoch: 9 | Batch Status: 3200/50000 (6%) | Loss: 1.196878
Train Epoch: 9 | Batch Status: 3840/50000 (8%) | Loss: 1.420938
Train Epoch: 9 | Batch Status: 4480/50000 (9%) | Loss: 1.046166
Train Epoch: 9 | Batch Status: 5120/50000 (10%) | Loss: 1.565482
Train Epoch: 9 | Batch Status: 5760/50000 (12%) | Loss: 1.310529
Train Epoch: 9 | Batch Status: 6400/50000 (13%) | Loss: 1.523646
Train Epoch: 9 | Batch Status: 7040/50000 (14%) | Loss: 1.249951
Train Epoch: 9 | Batch Status: 7680/50000 (15%) | Loss: 1.417551
Train Epoch: 9 | Batch Status: 8320/50000 (17%) | Loss: 1.223358
Train Epoch: 9 | Batch Status: 8960/50000 (18%) | Loss: 1.354413
Train Epoch: 9 | Batch Status: 9600/50000 (19%) | Loss: 1.202000
Train Epoch: 9 | Batch Status: 10240/50000 (20%) | Loss: 1.552799
Train Epoch: 9 | Batch Status: 10880/50000 (22%) | Loss: 1.292228
Train Epoch: 9 | Batch Status: 11520/50000 (23%) | Loss: 1.335931
Train Epoch: 9 | Batch Status: 12160/50000 (24%) | Loss: 1.160139
Train Epoch: 9 | Batch Status: 12800/50000 (26%) | Loss: 1.331580
Train Epoch: 9 | Batch Status: 13440/50000 (27%) | Loss: 1.244054
Train Epoch: 9 | Batch Status: 14080/50000 (28%) | Loss: 1.533060
Train Epoch: 9 | Batch Status: 14720/50000 (29%) | Loss: 1.354995
Train Epoch: 9 | Batch Status: 15360/50000 (31%) | Loss: 1.563544
Train Epoch: 9 | Batch Status: 16000/50000 (32%) | Loss: 1.456223
Train Epoch: 9 | Batch Status: 16640/50000 (33%) | Loss: 1.287812
Train Epoch: 9 | Batch Status: 17280/50000 (35%) | Loss: 1.271317
Train Epoch: 9 | Batch Status: 17920/50000 (36%) | Loss: 1.314949
Train Epoch: 9 | Batch Status: 18560/50000 (37%) | Loss: 1.094473
Train Epoch: 9 | Batch Status: 19200/50000 (38%) | Loss: 1.251171
Train Epoch: 9 | Batch Status: 19840/50000 (40%) | Loss: 1.387877
Train Epoch: 9 | Batch Status: 20480/50000 (41%) | Loss: 1.569596
Train Epoch: 9 | Batch Status: 21120/50000 (42%) | Loss: 1.681830
Train Epoch: 9 | Batch Status: 21760/50000 (43%) | Loss: 1.565155
Train Epoch: 9 | Batch Status: 22400/50000 (45%) | Loss: 1.178569
Train Epoch: 9 | Batch Status: 23040/50000 (46%) | Loss: 1.223829
Train Epoch: 9 | Batch Status: 23680/50000 (47%) | Loss: 1.348938
Train Epoch: 9 | Batch Status: 24320/50000 (49%) | Loss: 1.324960
Train Epoch: 9 | Batch Status: 24960/50000 (50%) | Loss: 1.442940
Train Epoch: 9 | Batch Status: 25600/50000 (51%) | Loss: 1.426445
Train Epoch: 9 | Batch Status: 26240/50000 (52%) | Loss: 1.628445
Train Epoch: 9 | Batch Status: 26880/50000 (54%) | Loss: 1.441506
Train Epoch: 9 | Batch Status: 27520/50000 (55%) | Loss: 1.225741
Train Epoch: 9 | Batch Status: 28160/50000 (56%) | Loss: 1.147281
Train Epoch: 9 | Batch Status: 28800/50000 (58%) | Loss: 1.051337
Train Epoch: 9 | Batch Status: 29440/50000 (59%) | Loss: 1.204811
Train Epoch: 9 | Batch Status: 30080/50000 (60%) | Loss: 1.367823
Train Epoch: 9 | Batch Status: 30720/50000 (61%) | Loss: 1.348654
Train Epoch: 9 | Batch Status: 31360/50000 (63%) | Loss: 1.289946
Train Epoch: 9 | Batch Status: 32000/50000 (64%) | Loss: 1.295187
Train Epoch: 9 | Batch Status: 32640/50000 (65%) | Loss: 1.053263
Train Epoch: 9 | Batch Status: 33280/50000 (66%) | Loss: 1.496231
Train Epoch: 9 | Batch Status: 33920/50000 (68%) | Loss: 1.348117
Train Epoch: 9 | Batch Status: 34560/50000 (69%) | Loss: 1.127224
Train Epoch: 9 | Batch Status: 35200/50000 (70%) | Loss: 1.402330
Train Epoch: 9 | Batch Status: 35840/50000 (72%) | Loss: 1.270785
Train Epoch: 9 | Batch Status: 36480/50000 (73%) | Loss: 1.105789
Train Epoch: 9 | Batch Status: 37120/50000 (74%) | Loss: 1.370912
Train Epoch: 9 | Batch Status: 37760/50000 (75%) | Loss: 1.267858
Train Epoch: 9 | Batch Status: 38400/50000 (77%) | Loss: 1.168727
Train Epoch: 9 | Batch Status: 39040/50000 (78%) | Loss: 1.252575
Train Epoch: 9 | Batch Status: 39680/50000 (79%) | Loss: 1.543765
Train Epoch: 9 | Batch Status: 40320/50000 (81%) | Loss: 1.494956
Train Epoch: 9 | Batch Status: 40960/50000 (82%) | Loss: 1.384263
Train Epoch: 9 | Batch Status: 41600/50000 (83%) | Loss: 1.571918
Train Epoch: 9 | Batch Status: 42240/50000 (84%) | Loss: 1.432993
Train Epoch: 9 | Batch Status: 42880/50000 (86%) | Loss: 1.425925
Train Epoch: 9 | Batch Status: 43520/50000 (87%) | Loss: 1.344589
Train Epoch: 9 | Batch Status: 44160/50000 (88%) | Loss: 1.246753
Train Epoch: 9 | Batch Status: 44800/50000 (90%) | Loss: 1.346797
Train Epoch: 9 | Batch Status: 45440/50000 (91%) | Loss: 1.356617
Train Epoch: 9 | Batch Status: 46080/50000 (92%) | Loss: 1.089832
Train Epoch: 9 | Batch Status: 46720/50000 (93%) | Loss: 1.312031
Train Epoch: 9 | Batch Status: 47360/50000 (95%) | Loss: 1.331420
Train Epoch: 9 | Batch Status: 48000/50000 (96%) | Loss: 1.159545
Train Epoch: 9 | Batch Status: 48640/50000 (97%) | Loss: 1.257049
Train Epoch: 9 | Batch Status: 49280/50000 (98%) | Loss: 1.284090
Train Epoch: 9 | Batch Status: 49920/50000 (100%) | Loss: 1.172301
Training time: 1m 27s
===========================
Test set: Average loss: 0.0240, Accuracy: 4668/10000 (47%)
Testing time: 1m 33s
Total Time: 14m 1s
Model was trained on cpu!
