# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJ_cUJTZfztM3s7eRSik7w1aEFD3AzVQ
"""

from __future__ import print_function # __future__에서 print_function을 불러옴
from torch import nn, optim, cuda # torch에서 nn, optim, cuda를 불러옴
from torch.utils import data  # torch.utils에서 data를 불러옴
from torchvision import datasets, transforms  # torchvision에서 datasets, transforms를 사용
import torch.nn.functional as F 
import time 

# Training settings
batch_size = 64 # 배치 사이즈 64
device = 'cuda' if cuda.is_available() else 'cpu' # 가능하다면 cuda로 gpu 사용
print(f'Training MNIST Model on {device}\n{"=" * 44}') 

# MNIST Dataset
train_dataset = datasets.MNIST(root='./mnist_data/',            # datasets를 통하여 MNIST데이터를 불러옴
                               train=True,                      # 훈련 데이터를 반환받음
                               transform=transforms.ToTensor(), # 현재 데이터를 파이토치 텐서로 변환
                               download=True)                   # 해당 경로에 MNIST데이터가 없다면 다운로드 받음
  
test_dataset = datasets.MNIST(root='./mnist_data/',             # datasets를 통하여 MNIST데이터를 불러옴
                              train=False,                      # 테스트 데이터를 반환받음
                              transform=transforms.ToTensor())  # 현재 데이터를 파이토치 텐서로 변환

# Data Loader (Input Pipeline)
train_loader = data.DataLoader(dataset=train_dataset,# dataloader를 사용하여 train_dataset를 불러오고, 64의 배치사이즈 지정, 셔플 사용
                                           batch_size=batch_size,
                                           shuffle=True)

test_loader = data.DataLoader(dataset=test_dataset, # dataloader를 사용하여 train_dataset를 불러오고, 64의 배치사이즈 지정, 셔플 사용X
                                          batch_size=batch_size,
                                          shuffle=False)


class Net(nn.Module): #  신경망 클래스 작성

    def __init__(self): 
        super(Net, self).__init__() 
        self.l1 = nn.Linear(784, 520) # input layer
        self.l2 = nn.Linear(520, 320) # hidden layer1
        self.l3 = nn.Linear(320, 240) # hidden layer2
        self.l4 = nn.Linear(240, 120) # hidden layer3
        self.l5 = nn.Linear(120, 10) # output layer

    def forward(self, x):
        x = x.view(-1, 784)  # Flatten the data (n, 1, 28, 28)-> (n, 784) 평탄화
        x = F.relu(self.l1(x))  # 평탄화한 x를 l1에 넣고, 활성화 relu함수에 넣은 뒤 결과를 x에 덮어씌운후 l2,l3,l4반복
        x = F.relu(self.l2(x))  
        x = F.relu(self.l3(x))  
        x = F.relu(self.l4(x))  
        return self.l5(x) # l5를 출력


model = Net() # model에 Net 클래스
model.to(device)  #gpu로 불러오기
criterion = nn.CrossEntropyLoss() # criterion에 CrossEntropyLoss 함수 사용
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.5)  # 최적화 함수로 경사하강법을 사용,모멘텀을 지정함으로
                                                                    #이전 이동값을 고려하여 일정비율만큼 다음값을 지정 (관성효과)


def train(epoch): #
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader): # train_loader를 이용하여 각각의 배치사이즈의 data, target를 불러옴
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad() 
        output = model(data)  
        loss = criterion(output, target)    # 예측값 output과 target의 loss 값
        loss.backward()                     # 역전파 실행
        optimizer.step()  
        if batch_idx % 10 == 0:
            print('Train Epoch: {} | Batch Status: {}/{} ({:.0f}%) | Loss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))


def test(): # 학습이 완료된 모델에 test데이터셋을 적용하여 제대로 학습이 되었나 확인하는 과정
    model.eval()
    test_loss = 0
    correct = 0
    for data, target in test_loader:  # test_loader
        data, target = data.to(device), target.to(device) #  GPU 사용
        output = model(data) 
        # sum up batch loss
        test_loss += criterion(output, target).item() # 테스트 loss 값 계산
        # get the index of the max
        pred = output.data.max(1, keepdim=True)[1]  # output.data.max함수로 예측
        correct += pred.eq(target.data.view_as(pred)).cpu().sum() # 정확도 계산

    test_loss /= len(test_loader.dataset)  
    print(f'===========================\nTest set: Average loss: {test_loss:.4f}, Accuracy: {correct}/{len(test_loader.dataset)} '
          f'({100. * correct / len(test_loader.dataset):.0f}%)')  # 예측이 맞았는지 계산


if __name__ == '__main__':
    since = time.time()         #유닉스 시간 정수부는 초단위이고, 소수부는 마이크로(micro) 초단위, 현재 시간정보 저장
    for epoch in range(1, 10):
        epoch_start = time.time()
        train(epoch)
        m, s = divmod(time.time() - epoch_start, 60) #divmod 나누어서 몫과 나머지 구함 
        print(f'Training time: {m:.0f}m {s:.0f}s')
        test()
        m, s = divmod(time.time() - epoch_start, 60)
        print(f'Testing time: {m:.0f}m {s:.0f}s')

    m, s = divmod(time.time() - since, 60)
    print(f'Total Time: {m:.0f}m {s:.0f}s\nModel was trained on {device}!')